# HIV Model Notebook

Annie Tor

In [1]:
# Configure Jupyter so figures appear in the notebook
%matplotlib inline

# Configure Jupyter to display the assigned value after an assignment
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

# import functions from the modsim.py module
from modsim import *

In [16]:
R = 0
L = 0
E = 0
V = 0
Gamma = 0
tau = 0
mu = 0
beta = 0
rho = 0
alpha = 0
delta = 0
pi = 0
sigma = 0

def calc_dR(Gamma, tau, mu, beta):
    dR = Gamma * tau - mu * state.R - beta * state.R * state.V
    return dR

def calc_dL(rho, beta, mu, alpha):
    dL = rho*beta*state.R*state.V - mu *state.L - alpha*state.L
    return dL

def calc_dE(rho, beta, alpha, delta):
    dE = (1 - rho)*beta*state.R*state.V + alpha*state.L + delta*state.E
    return dE

def calc_dV(pi, sigma):
    dV = pi*state.E - sigma *state.V
    return dV

state = State(R = R,
             L = L,
             E = E,
             V = V)

R    0
L    0
E    0
V    0
dtype: int64

In [17]:
system = System(calc_dR = calc_dR,
                calc_dL = calc_dL,
                calc_dE = calc_dE,
                calc_dV = calc_dV,
                Gamma = Gamma,
                tau = tau,
                mu = mu,
                beta = beta,
                rho = rho,
                alpha = alpha,
                delta = delta,
                pi = pi,
                sigma = sigma)

calc_dR    <function calc_dR at 0x00000284852989D8>
calc_dL    <function calc_dL at 0x00000284852F0268>
calc_dE    <function calc_dE at 0x00000284852F0B70>
calc_dV    <function calc_dV at 0x00000284852F0D90>
Gamma                                             0
tau                                               0
mu                                                0
beta                                              0
rho                                               0
alpha                                             0
delta                                             0
pi                                                0
sigma                                             0
dtype: object

In [ ]:
def update_func(state, system):
    state.R = state.R + system.calc_dR()